/*!
 * Copyright © 2015 Richard Huang <rickypc@users.noreply.github.com>
 * All rights reserved.
 */

export default {
  chinese: {
    children: [
      '唵 阿波嚧醯 盧迦帝 迦羅帝 夷醯唎 摩訶菩提薩埵 薩婆薩婆',
      '摩囉 摩囉 摩摩 醯唎馱孕',
      '俱盧俱盧 羯蒙',
      '度盧度盧 罰闍耶帝 摩訶罰闍耶帝',
      '陀囉陀囉 地唎尼室佛囉耶',
      '遮囉遮囉 摩摩 罰摩囉穆帝 隸',
      '伊醯移醯 室那室那 阿囉參 佛囉舍利',
      '罰沙罰參 佛囉舍哪',
      '呼嚧呼嚧 摩囉',
      '呼嚧呼嚧 醯利',
      '娑囉娑囉 悉唎悉唎 蘇嚧蘇嚧',
      '菩提夜菩提夜 菩馱夜菩馱夜 彌帝唎夜 那囉謹墀',
      '他利瑟尼那 波夜摩那 娑婆訶',
      '悉陀夜 娑婆訶',
      '摩訶悉陀夜 娑婆訶',
      '悉陀喻藝室皤囉耶 娑婆訶',
      '那囉謹墀 娑婆訶',
      '摩囉那囉 娑婆訶',
      '悉囉僧阿穆佉耶 娑婆訶',
      '娑婆摩何悉陀夜 娑婆訶',
      '者吉囉何悉陀夜 娑婆訶',
      '波摩羯悉陀夜 娑婆訶',
      '那囉謹墀皤伽囉耶 娑婆訶',
      '摩婆利勝羯囉夜 娑婆訶',
    ].join(' · '),
    // 大悲咒.
    title: '青頸陀羅尼',
  },
  lang: 'sa-IN',
  path: import.meta.url,
  sanskrit: {
    children: [
      'ॐ अपलोक लोकातिक्रान्त एहि हरे महाबोधिसत्त्व सर्पसर्प',
      'मर स्मर मम हृदयम्',
      'कुरुकुरु कर्म',
      'धुरुधुरु विजयते महाविजयते',
      'धरधर धारणीश्वराय',
      'चलचल मम विमलमूर्ते रे',
      'एह्येहि शिनशिन आर्षं प्रसरि',
      'विषविषं प्रणाशय',
      'हुलुहुलु मल्ल',
      'हुलुहुलु हरे',
      'सरसर सिरिसिरि सुरुसुरु',
      'बोधियबोधिय बोधयबोधय मैत्रिय नीलकण्ठ',
      'दर्शनेन प्रह्लादय मनः स्वाहा',
      'सिद्धाय स्वाहा',
      'महासिद्धाय स्वाहा',
      'सिद्धयोगेश्वराय स्वाहा',
      'नीलकण्ठाय स्वाहा',
      'वराहमुखाय स्वाहा',
      'नारसिंहमुखाय स्वाहा',
      'सर्वमहासिद्धाय स्वाहा',
      'चक्रहस्ताय स्वाहा',
      'पद्महस्ताय स्वाहा',
      'नीलकण्ठव्याघ्राय स्वाहा',
      'महाबलिशङ्कराय स्वाहा',
    ].join(' । '),
    repeat: { condensed: 19, roll: 7, wheel: 7 },
    // महाकारुणिक धारणी.
    title: 'नीलकण्ठ धारणी',
    typography: {
      wheel: { default: 5.9, title: 4 },
    },
  },
  translation: {
    title: 'Great Compassion Dhāraṇī',
  },
  transliteration: {
    children: [
      'oṃ apaloka lokātikrānta ehi hare mahābodhisattva sarpa-sarpa',
      'smara smara mama hṛdayam',
      'kuru-kuru karma',
      'dhuru-dhuru vijayate mahā-vijayate',
      'dhara-dhara dhāraṇī-śvarāya',
      'cala-cala mama vimala-mūrtte re',
      'ehy-ehi śina-śina ārṣam prasari',
      'viṣa-viṣaṃ praṇāśaya',
      'hulu-hulu malla',
      'hulu-hulu hare',
      'sara-sara siri-siri suru-suru',
      'bodhiya-bodhiya bodhaya-bodhaya maitriya nīlakaṇṭha',
      'darśanena prahlādaya manaḥ svāhā',
      'siddhāya svāhā',
      'mahāsiddhāya svāhā',
      'siddha-yogeśvarāya svāhā',
      'nīlakaṇṭhāya svāhā',
      'varāha-mukhāya svāhā',
      'narasiṃha-mukhāya svāhā',
      'sarva-mahā-siddhāya svāhā',
      'cakra-hastāya svāhā',
      'padma-hastāya svāhā',
      'nīlakaṇṭha-vyāghrāya svāhā',
      'mahābali-śankarāya svāhā',
    ].join(' । '),
    // Mahākaruṇika Dhāraṇī.
    title: 'Nīlakaṇṭha Dhāraṇī',
  },
};
