/*!
 * Copyright © 2015 Richard Huang <rickypc@users.noreply.github.com>
 * All rights reserved.
 */

const phrases = '#buddhism/practical-daily-practice/phrases';

export default [
  ['id_ID-news_tts-medium', `${phrases}/_abhiseka.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_abhiseka_puja.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_ahvana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_aksara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_aksobhya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_amitabha.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_amoghapasa_mani_puja.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_amoghapasa_padma_usnisa.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_anekajati.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_bhagavate_maju.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara_astaghora_tarani_sutra.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara_bijaksara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara_nama.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara_sataksara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_arya_tara_svapratijna_nama.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_avalokitesvara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_bhaisajyaguru.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_bodhi_garbhalamkara_laksa.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_caksu_unmilana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_catvary_apramanani.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_darsana_mukta.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_dasa_atyaya_mantrah.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_dasa_cula_dharani.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_dasa_mukta_mantrah.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_dhanadatara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_dharma.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_ekadasamukhalokesvara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_ekajati.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_guhyadhatu_karanda.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_japa.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_maha_cakra_vajra.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_maha_cundi_durga.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_mahamani_ratana_patimakara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_mahamani_vipulavimana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_mahavairocana_sarvadurgati_parisodhana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_maitreya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_mala.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_mandala_puja.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_manjusri.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_milarepa.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_namaskara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_panca_bhuta.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_panca_jambhala.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_panca_jnana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_panca_maha_suddhi.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_panca_sila.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_parinamana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_prajna_paramita.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_prarthanasiddhih.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_pratistha.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_pratityasamutpada.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_pratityasamutpada_samudaya_nirodha.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_rakta_tara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_rasmi_vimala_dharani.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_rasmi_vimala_hrdaya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_ratnadhvaja_parikrama.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_ratnasikhin.ts`],
  ['en_US-hfc_male-medium', `${phrases}/_ricky_huang.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sadja_mukta.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sakyamuni.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_samgharama.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sapta_atitabuddha_karasaniya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_saranagamana_cittotpada.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sat_dharmakaya_sarirah.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sita_tara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sridevi.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sukhavativyuha.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_sunyata.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_supratistha.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_surangama.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_trikaya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_trimula_sarana.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_usnisa_sitatapatra.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_usnisa_vijaya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vairocana_sarvakata_danavidhih.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vajra_dhara.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vajra_gita.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vajra_kilaya.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vasuratna.ts`],
  ['id_ID-news_tts-medium', `${phrases}/_vimala_usnisa.ts`],
];
